[project]
name = "ochre_generic_inverter_model"
version = "0.1.0"
description = ""
authors = [
    {name = "MidrarAdham",email = "midrar.adhm@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ochre-nrel (>=0.9.2,<0.10.0)",
    "numpy (>=1.26,<2.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "helics (>=3.6.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
